name: Ensure PR has Reviewer

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  check-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR has reviewer
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const { data: reviews } = await github.pulls.listReviews({
              owner,
              repo,
              pull_number: prNumber,
            });

            const reviewers = context.payload.pull_request.requested_reviewers;
            const assignedReviewers = reviewers.length;

            if (assignedReviewers === 0) {
              core.setFailed("This pull request has no reviewers assigned. Please assign at least one reviewer.");
            } else {
              console.log(`This pull request has ${assignedReviewers} reviewers.`);
            }
